---
- name: "configuration play."
  hosts: web
  user: ubuntu
  become: true
  gather_facts: false
  vars:
    - ansible_python_interpreter: /usr/bin/python3
    - ansible_host_key_checking: false
    - ansible_stdout_callback: yaml

  pre_tasks:
    - name: "wait 300 seconds for target connection to become reachable/usable."
      wait_for_connection:
        timeout: 300

    - name: "install python for Ansible."
      become: true
      shell: |
        sudo apt-get update -y
        sudo apt-get install -y nodejs 
        sudo apt-get install -y Python3.8
        sudo apt-get install -y npm

  roles:
    - deploy
