---
- name: "Creates backend app directory"
  file:
    path: /home/ubuntu/app
    state: directory

- name: "Unarchive backend files"
  unarchive:
    src: files/artifact.tar.gz
    dest: /home/ubuntu/app
    owner: ubuntu

- name: Install dependencies
  become: true
  shell: |
    cd /home/ubuntu/app
    npm install
    npm install pm2

- name: Start backend
  shell: |
    export TYPEORM_HOST="{{ lookup('env', 'TYPEORM_HOST') }}"
    export TYPEORM_ENTITIES="{{ lookup('env', 'TYPEORM_ENTITIES') }}"
    export TYPEORM_USERNAME="{{ lookup('env', 'TYPEORM_USERNAME') }}"
    export TYPEORM_PASSWORD="{{ lookup('env', 'TYPEORM_PASSWORD') }}"
    export TYPEORM_DATABASE="{{ lookup('env', 'TYPEORM_DATABASE') }}"

    cd /home/ubuntu/app
    pm2 stop default
    pm2 start npm -- start

# - name: "Unarchive backend files"
#   unarchive:
#     src: files/artifact.tar.gz
#     dest: ~/app

# - name: "Installing Node Dependencies"
#   shell: |
#     cd ~/app
#     npm install

# - name: "Executing Node app with PM2"
#   shell: |
#     cd ~/app
#     pm2 stop default
#     pm2 start npm -- start
#   register: execute_node

# - name: print message
#   debug:
#     msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
