---
- name: "Creates backend app directory"
  file:
    path: /home/ubuntu/app
    state: directory
    mode: 0755

- name: Copy artifact
  become: true
  copy:
    src: files/artifact.tar.gz
    dest: /home/ubuntu/app/artifact.tar.gz

- name: Extract artifact files
  become: true
  shell: |
    cd /home/ubuntu/app
    tar -xvf artifact.tar.gz

- name: "Executing Node app with PM2"
  shell: |
    cd /home/ubuntu/app
    pm2 stop default
    pm2 start npm -- start
    pm2 start npm -- start --wait-ready
  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

- name: "Configure pm2 to start as service"
  become: true
  shell: |
    env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
